### ISSUE TITLE
Bug: `NewMoon_CAST` nil value causing error in druid.lua rotation logic

### ISSUE THREAD

**Issue by moderncodes** [Vae2009/ConRO_Druid#7] opened 2024-11-02 06:37 UTC
A **nil** comparison error occurs in the _New Moon_ spell rotation logic. The `_NewMoon_CAST` variable is not being properly initialized or updated before comparison operations.

### Error Message
```lua
3x ConRO_Druid/druid.lua:414: attempt to compare nil with number
[string "@ConRO_Druid/druid.lua"]:414: in function `NextSpell'
[string "@ConRO/core.lua"]:2427: in function `?'
[string "@APR/APR-Core/libs/AceTimer-3.0-17/AceTimer-3.0.lua"]:55: in function <...dOns/APR/APR-Core/libs/AceTimer-3.0/AceTimer-3.0.lua:50>
```
### The error occurs in 
https://github.com/Vae2009/ConRO_Druid/blob/2cdf63b1d05be0c2a7a56c24987663e3551725e0/druid.lua#L414

### Expected Behavior
- The addon should properly track and update New Moon cast timing
- The rotation logic should handle cases where New Moon cast timing is not available

### Proposed Fix
```lua
_NewMoon_CAST = _NewMoon_CAST or 0  -- Add default value

-- Or update the condition to include nil check:
if _NewMoon_RDY and _NewMoon_CAST and ... then
```

### Environment
- World of Warcraft Version: 11.0.5.57388
- ConRO Version: v11.0.03
- ConRO_Druid Version: v11.0.1
- Character Spec: Elune's Chosen

## PS 
_I could potentially contribute, but it seems like you are ignoring pull requests, so I won't even bother._
Thank you!

**Comment by Vae2009** [comment] 2024-11-02 20:47
I appreciate the report. The issue is actually an error on my part where I called for the cast time from the Spell charges function and not the ability ready function. It will be fixed in next upload.

Thanks again.

**Closed as completed by Vae2009** 2024-11-02 20:47 UTC
